Removing an exclusion rule from the d1_solr_extensions pom.xml since we're getting a NoClassDefFoundError: org/bouncycastle/openssl/PEMParser (it had also been removed from the shared libs)
refs #3226